// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportToolsServerDbPart.Db;

#nullable disable

namespace SupportToolsServerDbTools.DbMigration.Migrations
{
    [DbContext(typeof(SupportToolsServerDbContext))]
    [Migration("20261006113002_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportToolsServerCore.Domain.ApiClients.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Server")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApiClients");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseFoldersSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Backup")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Data")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("DataLog")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("DatabaseServerConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseServerConnectionId", "Name")
                        .IsUnique();

                    b.ToTable("DatabaseFoldersSets", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConnectionTimeOut")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseServerProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DbWebAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Encrypt")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RemoteDbConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ServerAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ServerPass")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ServerUser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("WindowsNtIntegratedSecurity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DbWebAgentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseServerConnections");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DeploymentEnvironments.DeploymentEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DotnetTools.DotnetTool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaxVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DotnetTools");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.EditorConfigFileTypes.EditorConfigFileType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EditorConfigFileTypes");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.FileStorages.FileStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileNameMaxLength")
                        .HasColumnType("int");

                    b.Property<int>("FileSizeSplitPositionInRow")
                        .HasColumnType("int");

                    b.Property<string>("FileStoragePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("FtpSiteLsFileOffset")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileStorages");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.GitIgnoreFileTypes.GitIgnoreFileType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GitIgnoreFileTypes");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.GitRepos.GitRepo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GitIgnoreFileTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("GitIgnoreFileTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GitRepos");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.NpmPackages.NpmPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(214)
                        .HasColumnType("nvarchar(214)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NpmPackages");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.ProjectTemplates.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ReactTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportProjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TestProjectShortName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseCarcass")
                        .HasColumnType("bit");

                    b.Property<bool>("UseDatabase")
                        .HasColumnType("bit");

                    b.Property<bool>("UseDbPartFolderForDatabaseProjects")
                        .HasColumnType("bit");

                    b.Property<bool>("UseFluentValidation")
                        .HasColumnType("bit");

                    b.Property<bool>("UseHttps")
                        .HasColumnType("bit");

                    b.Property<bool>("UseIdentity")
                        .HasColumnType("bit");

                    b.Property<bool>("UseMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("UseReCounter")
                        .HasColumnType("bit");

                    b.Property<bool>("UseReact")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSignalR")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ReactTemplateId");

                    b.ToTable("ProjectTemplates");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiContractsProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AppSetEnKeysJsonFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("DataSeederRulesByTableStartupProjectFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("DbContextName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DbContextProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("EditorConfigFileTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExcludesRulesParametersFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("KeyGuidPart")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MainProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("int");

                    b.Property<string>("MigrationProjectFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("MigrationSqlFilesFolder")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("MigrationStartupProjectFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("MinorVersion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewDataSeedingClassLibProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OldDataConvertorForDataSeeder")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("PairedDbObjectsResultFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ParametersFileDateMask")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametersFileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrepareProdCopyDatabaseProjectFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("PrepareProdCopyDatabaseProjectParametersFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ProgramArchiveDateMask")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramArchiveExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectFolderName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ProjectGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectSecurityFolderPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ProjectShortPrefix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScaffoldSeederProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeedProjectFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SeedProjectParametersFilePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SolutionFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SpaProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseAlternativeWebAgent")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("EditorConfigFileTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectAllowedTool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ToolName")
                        .IsUnique();

                    b.ToTable("ProjectAllowedTools", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndpointName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EndpointRoute")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireAuthorization")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("SendMessageToCurrentUser")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("ProjectEndpoints", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectGitRepo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GitRepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GitRepoId");

                    b.HasIndex("ProjectId", "GitRepoId", "Kind")
                        .IsUnique();

                    b.ToTable("ProjectGitRepos", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectNpmPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NpmPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NpmPackageId");

                    b.HasIndex("ProjectId", "NpmPackageId")
                        .IsUnique();

                    b.ToTable("ProjectNpmPackages", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectRedundantFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "FileName")
                        .IsUnique();

                    b.ToTable("ProjectRedundantFiles", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectRouteClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Base")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Root")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("ProjectRouteClasses", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ServerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiVersionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppSettingsEncodedJsonFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("AppSettingsJsonSourceFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServerSidePort")
                        .HasColumnType("int");

                    b.Property<string>("ServiceUserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("WebAgentForCheckId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ServerId");

                    b.HasIndex("WebAgentForCheckId");

                    b.HasIndex("ProjectId", "ServerId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("ServerInfos", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ServerInfoAllowedTool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServerInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ServerInfoId", "ToolName")
                        .IsUnique();

                    b.ToTable("ServerInfoAllowedTools", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.ReactAppTemplates.ReactAppTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(214)
                        .HasColumnType("nvarchar(214)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReactAppTemplates");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Runtimes.Runtime", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Runtimes");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Servers.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilesUserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FilesUsersGroupName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RuntimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServerSideDeployFolder")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ServerSideDownloadFolder")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("WebAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WebAgentInstallerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RuntimeId");

                    b.HasIndex("WebAgentId");

                    b.HasIndex("WebAgentInstallerId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileStorageForExchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocalPackageManagerWebApiClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediatRLicenseKey")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ParametersFileDateMask")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametersFileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramArchiveDateMask")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramArchiveExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceDescriptionSignature")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SmartSchemaForExchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SmartSchemaForLocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UploadTempExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("FileStorageForExchangeId");

                    b.HasIndex("LocalPackageManagerWebApiClientId");

                    b.HasIndex("SmartSchemaForExchangeId");

                    b.HasIndex("SmartSchemaForLocalId");

                    b.ToTable("GlobalSettings", t =>
                        {
                            t.HasCheckConstraint("CK_GlobalSettings_Singleton", "[Id] = '00000000-0000-0000-0000-000000000001'");
                        });
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.ProjectCreatorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DatabaseExchangeFileStorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeveloperDbConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FakeHostProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IndentSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductionEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductionServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectsFolderPathReal")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SecretsFolderPathReal")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid?>("UseSmartSchemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DatabaseExchangeFileStorageId");

                    b.HasIndex("DeveloperDbConnectionId");

                    b.HasIndex("ProductionEnvironmentId");

                    b.HasIndex("ProductionServerId");

                    b.HasIndex("UseSmartSchemaId");

                    b.ToTable("ProjectCreatorSettings", t =>
                        {
                            t.HasCheckConstraint("CK_ProjectCreatorSettings_Singleton", "[Id] = '00000000-0000-0000-0000-000000000001'");
                        });
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LastPreserveCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SmartSchemas");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchemaDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PreserveCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SmartSchemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SmartSchemaId", "PeriodType")
                        .IsUnique();

                    b.ToTable("SmartSchemaDetails", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.StoredFiles.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseFoldersSet", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                        .WithMany("DatabaseFoldersSets")
                        .HasForeignKey("DatabaseServerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("DbWebAgentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.GitRepos.GitRepo", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.GitIgnoreFileTypes.GitIgnoreFileType", null)
                        .WithMany()
                        .HasForeignKey("GitIgnoreFileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.ProjectTemplates.ProjectTemplate", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.ReactAppTemplates.ReactAppTemplate", null)
                        .WithMany()
                        .HasForeignKey("ReactTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.Project", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.EditorConfigFileTypes.EditorConfigFileType", null)
                        .WithMany()
                        .HasForeignKey("EditorConfigFileTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SupportToolsServerCore.Domain.Projects.DatabaseParameters", "DevDatabaseParameters", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BackupFileExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("BackupNameMiddlePart")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupNamePrefix")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupType")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("CommandTimeOut")
                                .HasColumnType("int");

                            b1.Property<bool?>("Compress")
                                .HasColumnType("bit");

                            b1.Property<string>("DatabaseName")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("DatabaseRecoveryModel")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("DateMask")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("DbConnectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DbServerFoldersSetName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("FileStorageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("SkipBackupBeforeRestore")
                                .HasColumnType("bit");

                            b1.Property<Guid?>("SmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("Verify")
                                .HasColumnType("bit");

                            b1.HasKey("ProjectId");

                            b1.HasIndex("DbConnectionId");

                            b1.HasIndex("FileStorageId");

                            b1.HasIndex("SmartSchemaId");

                            b1.ToTable("Projects");

                            b1.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                                .WithMany()
                                .HasForeignKey("DbConnectionId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                                .WithMany()
                                .HasForeignKey("FileStorageId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("SmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("SupportToolsServerCore.Domain.Projects.DatabaseParameters", "ProdCopyDatabaseParameters", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BackupFileExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("BackupNameMiddlePart")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupNamePrefix")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupType")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("CommandTimeOut")
                                .HasColumnType("int");

                            b1.Property<bool?>("Compress")
                                .HasColumnType("bit");

                            b1.Property<string>("DatabaseName")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("DatabaseRecoveryModel")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("DateMask")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("DbConnectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DbServerFoldersSetName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("FileStorageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("SkipBackupBeforeRestore")
                                .HasColumnType("bit");

                            b1.Property<Guid?>("SmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("Verify")
                                .HasColumnType("bit");

                            b1.HasKey("ProjectId");

                            b1.HasIndex("DbConnectionId");

                            b1.HasIndex("FileStorageId");

                            b1.HasIndex("SmartSchemaId");

                            b1.ToTable("Projects");

                            b1.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                                .WithMany()
                                .HasForeignKey("DbConnectionId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                                .WithMany()
                                .HasForeignKey("FileStorageId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("SmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.Navigation("DevDatabaseParameters");

                    b.Navigation("ProdCopyDatabaseParameters");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectAllowedTool", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.Projects.Project", null)
                        .WithMany("AllowedTools")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectEndpoint", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.Projects.Project", null)
                        .WithMany("Endpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectGitRepo", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.GitRepos.GitRepo", null)
                        .WithMany()
                        .HasForeignKey("GitRepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportToolsServerCore.Domain.Projects.Project", null)
                        .WithMany("GitRepos")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectNpmPackage", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.NpmPackages.NpmPackage", null)
                        .WithMany()
                        .HasForeignKey("NpmPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportToolsServerCore.Domain.Projects.Project", null)
                        .WithMany("NpmPackages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectRedundantFile", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.Projects.Project", null)
                        .WithMany("RedundantFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ProjectRouteClass", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.Projects.Project", null)
                        .WithMany("RouteClasses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ServerInfo", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.DeploymentEnvironments.DeploymentEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportToolsServerCore.Domain.Projects.Project", null)
                        .WithMany("ServerInfos")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportToolsServerCore.Domain.Servers.Server", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("WebAgentForCheckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SupportToolsServerCore.Domain.Projects.DatabaseParameters", "CurrentDatabaseParameters", b1 =>
                        {
                            b1.Property<Guid>("ServerInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BackupFileExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("BackupNameMiddlePart")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupNamePrefix")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupType")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("CommandTimeOut")
                                .HasColumnType("int");

                            b1.Property<bool?>("Compress")
                                .HasColumnType("bit");

                            b1.Property<string>("DatabaseName")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("DatabaseRecoveryModel")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("DateMask")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("DbConnectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DbServerFoldersSetName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("FileStorageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("SkipBackupBeforeRestore")
                                .HasColumnType("bit");

                            b1.Property<Guid?>("SmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("Verify")
                                .HasColumnType("bit");

                            b1.HasKey("ServerInfoId");

                            b1.HasIndex("DbConnectionId");

                            b1.HasIndex("FileStorageId");

                            b1.HasIndex("SmartSchemaId");

                            b1.ToTable("ServerInfos");

                            b1.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                                .WithMany()
                                .HasForeignKey("DbConnectionId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                                .WithMany()
                                .HasForeignKey("FileStorageId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("ServerInfoId");

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("SmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("SupportToolsServerCore.Domain.Projects.DatabaseParameters", "NewDatabaseParameters", b1 =>
                        {
                            b1.Property<Guid>("ServerInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BackupFileExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("BackupNameMiddlePart")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupNamePrefix")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BackupType")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("CommandTimeOut")
                                .HasColumnType("int");

                            b1.Property<bool?>("Compress")
                                .HasColumnType("bit");

                            b1.Property<string>("DatabaseName")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("DatabaseRecoveryModel")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("DateMask")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("DbConnectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DbServerFoldersSetName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("FileStorageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("SkipBackupBeforeRestore")
                                .HasColumnType("bit");

                            b1.Property<Guid?>("SmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("Verify")
                                .HasColumnType("bit");

                            b1.HasKey("ServerInfoId");

                            b1.HasIndex("DbConnectionId");

                            b1.HasIndex("FileStorageId");

                            b1.HasIndex("SmartSchemaId");

                            b1.ToTable("ServerInfos");

                            b1.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                                .WithMany()
                                .HasForeignKey("DbConnectionId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                                .WithMany()
                                .HasForeignKey("FileStorageId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("ServerInfoId");

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("SmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.Navigation("CurrentDatabaseParameters");

                    b.Navigation("NewDatabaseParameters");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ServerInfoAllowedTool", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.Projects.ServerInfo", null)
                        .WithMany("AllowedTools")
                        .HasForeignKey("ServerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Servers.Server", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.Runtimes.Runtime", null)
                        .WithMany()
                        .HasForeignKey("RuntimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("WebAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("WebAgentInstallerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.GlobalSettings", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                        .WithMany()
                        .HasForeignKey("FileStorageForExchangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("LocalPackageManagerWebApiClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany()
                        .HasForeignKey("SmartSchemaForExchangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany()
                        .HasForeignKey("SmartSchemaForLocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SupportToolsServerCore.Domain.Settings.DatabasesBackupFilesExchange", "DatabasesBackupFilesExchange", b1 =>
                        {
                            b1.Property<Guid>("GlobalSettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DownloadTempExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("ExchangeFileStorageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ExchangeSmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("LocalSmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UploadTempExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("GlobalSettingsId");

                            b1.HasIndex("ExchangeFileStorageId");

                            b1.HasIndex("ExchangeSmartSchemaId");

                            b1.HasIndex("LocalSmartSchemaId");

                            b1.ToTable("GlobalSettings");

                            b1.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                                .WithMany()
                                .HasForeignKey("ExchangeFileStorageId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("ExchangeSmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("GlobalSettingsId");

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("LocalSmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.Navigation("DatabasesBackupFilesExchange")
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.ProjectCreatorSettings", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                        .WithMany()
                        .HasForeignKey("DatabaseExchangeFileStorageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                        .WithMany()
                        .HasForeignKey("DeveloperDbConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.DeploymentEnvironments.DeploymentEnvironment", null)
                        .WithMany()
                        .HasForeignKey("ProductionEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.Servers.Server", null)
                        .WithMany()
                        .HasForeignKey("ProductionServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany()
                        .HasForeignKey("UseSmartSchemaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchemaDetail", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany("Details")
                        .HasForeignKey("SmartSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", b =>
                {
                    b.Navigation("DatabaseFoldersSets");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.Project", b =>
                {
                    b.Navigation("AllowedTools");

                    b.Navigation("Endpoints");

                    b.Navigation("GitRepos");

                    b.Navigation("NpmPackages");

                    b.Navigation("RedundantFiles");

                    b.Navigation("RouteClasses");

                    b.Navigation("ServerInfos");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Projects.ServerInfo", b =>
                {
                    b.Navigation("AllowedTools");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
