// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportToolsServerDbPart.Db;

#nullable disable

namespace SupportToolsServerDbTools.DbMigration.Migrations
{
    [DbContext(typeof(SupportToolsServerDbContext))]
    [Migration("20261005113410_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportToolsServerCore.Domain.ApiClients.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Server")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApiClients");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseFoldersSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Backup")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Data")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("DataLog")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("DatabaseServerConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseServerConnectionId", "Name")
                        .IsUnique();

                    b.ToTable("DatabaseFoldersSets", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConnectionTimeOut")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseServerProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DbWebAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Encrypt")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RemoteDbConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ServerAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ServerPass")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ServerUser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("WindowsNtIntegratedSecurity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DbWebAgentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseServerConnections");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DeploymentEnvironments.DeploymentEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DotnetTools.DotnetTool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaxVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DotnetTools");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.EditorConfigFileTypes.EditorConfigFileType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EditorConfigFileTypes");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.FileStorages.FileStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileNameMaxLength")
                        .HasColumnType("int");

                    b.Property<int>("FileSizeSplitPositionInRow")
                        .HasColumnType("int");

                    b.Property<string>("FileStoragePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("FtpSiteLsFileOffset")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileStorages");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.GitIgnoreFileTypes.GitIgnoreFileType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GitIgnoreFileTypes");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.GitRepos.GitRepo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GitIgnoreFileTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("GitIgnoreFileTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GitRepos");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.NpmPackages.NpmPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(214)
                        .HasColumnType("nvarchar(214)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NpmPackages");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.ProjectTemplates.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ReactTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportProjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TestProjectShortName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseCarcass")
                        .HasColumnType("bit");

                    b.Property<bool>("UseDatabase")
                        .HasColumnType("bit");

                    b.Property<bool>("UseDbPartFolderForDatabaseProjects")
                        .HasColumnType("bit");

                    b.Property<bool>("UseFluentValidation")
                        .HasColumnType("bit");

                    b.Property<bool>("UseHttps")
                        .HasColumnType("bit");

                    b.Property<bool>("UseIdentity")
                        .HasColumnType("bit");

                    b.Property<bool>("UseMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("UseReCounter")
                        .HasColumnType("bit");

                    b.Property<bool>("UseReact")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSignalR")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ReactTemplateId");

                    b.ToTable("ProjectTemplates");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.ReactAppTemplates.ReactAppTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(214)
                        .HasColumnType("nvarchar(214)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReactAppTemplates");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Runtimes.Runtime", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Runtimes");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Servers.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilesUserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FilesUsersGroupName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RuntimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServerSideDeployFolder")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ServerSideDownloadFolder")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("WebAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WebAgentInstallerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RuntimeId");

                    b.HasIndex("WebAgentId");

                    b.HasIndex("WebAgentInstallerId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileStorageForExchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocalPackageManagerWebApiClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediatRLicenseKey")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ParametersFileDateMask")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametersFileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramArchiveDateMask")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramArchiveExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceDescriptionSignature")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SmartSchemaForExchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SmartSchemaForLocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UploadTempExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("FileStorageForExchangeId");

                    b.HasIndex("LocalPackageManagerWebApiClientId");

                    b.HasIndex("SmartSchemaForExchangeId");

                    b.HasIndex("SmartSchemaForLocalId");

                    b.ToTable("GlobalSettings", t =>
                        {
                            t.HasCheckConstraint("CK_GlobalSettings_Singleton", "[Id] = '00000000-0000-0000-0000-000000000001'");
                        });
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.ProjectCreatorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DatabaseExchangeFileStorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeveloperDbConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FakeHostProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IndentSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductionEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductionServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectsFolderPathReal")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SecretsFolderPathReal")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid?>("UseSmartSchemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DatabaseExchangeFileStorageId");

                    b.HasIndex("DeveloperDbConnectionId");

                    b.HasIndex("ProductionEnvironmentId");

                    b.HasIndex("ProductionServerId");

                    b.HasIndex("UseSmartSchemaId");

                    b.ToTable("ProjectCreatorSettings", t =>
                        {
                            t.HasCheckConstraint("CK_ProjectCreatorSettings_Singleton", "[Id] = '00000000-0000-0000-0000-000000000001'");
                        });
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LastPreserveCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SmartSchemas");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchemaDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PreserveCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SmartSchemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SmartSchemaId", "PeriodType")
                        .IsUnique();

                    b.ToTable("SmartSchemaDetails", (string)null);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseFoldersSet", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                        .WithMany("DatabaseFoldersSets")
                        .HasForeignKey("DatabaseServerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("DbWebAgentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.GitRepos.GitRepo", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.GitIgnoreFileTypes.GitIgnoreFileType", null)
                        .WithMany()
                        .HasForeignKey("GitIgnoreFileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.ProjectTemplates.ProjectTemplate", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.ReactAppTemplates.ReactAppTemplate", null)
                        .WithMany()
                        .HasForeignKey("ReactTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Servers.Server", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.Runtimes.Runtime", null)
                        .WithMany()
                        .HasForeignKey("RuntimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("WebAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("WebAgentInstallerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.GlobalSettings", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                        .WithMany()
                        .HasForeignKey("FileStorageForExchangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.ApiClients.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("LocalPackageManagerWebApiClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany()
                        .HasForeignKey("SmartSchemaForExchangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany()
                        .HasForeignKey("SmartSchemaForLocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SupportToolsServerCore.Domain.Settings.DatabasesBackupFilesExchange", "DatabasesBackupFilesExchange", b1 =>
                        {
                            b1.Property<Guid>("GlobalSettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DownloadTempExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid?>("ExchangeFileStorageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ExchangeSmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("LocalSmartSchemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UploadTempExtension")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("GlobalSettingsId");

                            b1.HasIndex("ExchangeFileStorageId");

                            b1.HasIndex("ExchangeSmartSchemaId");

                            b1.HasIndex("LocalSmartSchemaId");

                            b1.ToTable("GlobalSettings");

                            b1.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                                .WithMany()
                                .HasForeignKey("ExchangeFileStorageId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("ExchangeSmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("GlobalSettingsId");

                            b1.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                                .WithMany()
                                .HasForeignKey("LocalSmartSchemaId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.Navigation("DatabasesBackupFilesExchange")
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.Settings.ProjectCreatorSettings", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.FileStorages.FileStorage", null)
                        .WithMany()
                        .HasForeignKey("DatabaseExchangeFileStorageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", null)
                        .WithMany()
                        .HasForeignKey("DeveloperDbConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.DeploymentEnvironments.DeploymentEnvironment", null)
                        .WithMany()
                        .HasForeignKey("ProductionEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.Servers.Server", null)
                        .WithMany()
                        .HasForeignKey("ProductionServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany()
                        .HasForeignKey("UseSmartSchemaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchemaDetail", b =>
                {
                    b.HasOne("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", null)
                        .WithMany("Details")
                        .HasForeignKey("SmartSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.DatabaseServerConnections.DatabaseServerConnection", b =>
                {
                    b.Navigation("DatabaseFoldersSets");
                });

            modelBuilder.Entity("SupportToolsServerCore.Domain.SmartSchemas.SmartSchema", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
